- name: enable services
  service:
    name: apache2
    state: started
    
- name: disable default vhost
  command: a2dissite 000-default.conf

- name: reload apache2 service
  service:
    name: apache2
    state: reloaded
